config/routes.rb
Moka::Application.routes.draw do
  filter :locale

  devise_for :users, controllers: {
                                    omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations"
                                  }

  devise_scope :user do
    get '/users/auth/:provider/battles/:battle_id' => 'users/omniauth_callbacks#share_battle'
    get '/users/auth/:provider/friends' => 'users/omniauth_callbacks#find_friends'
    get '/users/auth/:provider/setup', :to => 'users/omniauth_callbacks#setup'
  end

  get "users/facebook_friends" => "users#facebook_friends", :as => :user_facebook_friends
  get "users/sign_in_popup"    => "users#sign_in_popup",    :as => :user_sign_in_popup
  resources :users, :only => [:show, :index, :edit, :update] do
    resources :friendships, :only => [:create, :destroy, :index]
    resource :email_settings, :only => [:edit, :update]
  end
  get "users/:id/following" => "users#following", :as => :user_following
  get "users/:id/followers" => "users#followers", :as => :user_followers
  get "users/edit/social"   => "users#social",    :as => :user_social

  resources :battles, :except => [:index]
  get "hashtags/:hashtag" => "battles#hashtag", :as => :hashtag
  get "search(/:search)" => "searches#search", :as => :search

  resources :votes, :only => [:create]
  resources :notifications, :only => [:index]
  get "notifications_dropdown" => "notifications#dropdown", :as => :notifications_dropdown

  resources :options, :except => [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :comments, :only => [:index, :create, :destroy]
  end
  get "options/:id/votes" => "options#votes", :as => :option_votes

  get '/.well-known/acme-challenge/:id' => 'letsencrypt#challenge'

  get "locale" => 'users#locale', :as => :set_locale

  root :to => "users#home"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  resourcify
  paginates_per 8

  belongs_to :user
  belongs_to :option
  has_one :battle, through: :option
  attr_accessible :body, :user_id

  validates :body, presence: true
  validates :user_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]

  load_and_authorize_resource :option
  load_and_authorize_resource :comment, :through => :option, :except => [:index]

  def create
    if @comment.save
      @user = current_user
      @option.battle.user.receive_comment_notification_from(@user, @option) unless @user == @option.battle.user

      users = []
      @option.comments.each do |comment|
        users.push(comment.user)
      end
      users.delete(@option.battle.user)
      users.uniq.each do |user|
        user.receive_comment_answer_notification_from(@user, @option) unless @user == user
      end

      @new_comment = Comment.new()
      respond_to do |format|
        format.js {}
      end
    else
      respond_to do |format|
        format.js { render 'comments/reload_form' }
      end
    end
  end

  def index
    @user = current_user
    if not @user
      respond_to do |format|
        format.js { render 'comments/unsigned_user' }
      end
      return
    end

    authorize! :index, Comment
    @comment = Comment.new()

    @comments = @option.ordered_comments(params[:page])
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    @comment_id = @comment.id
    @comment.destroy
    respond_to do |format|
      format.js {}
    end
  end

end

app/views/comments/_box.html.erb
<div class="span<%= size %>">
  <%= render('comments/index', option: option) %>
</div>

app/views/comments/_comment.html.erb
<tr class="comment<%= comment[:id] %>">
  <td>
    <div class="comment-avatar">
      <%= link_to(image_tag(comment.user.avatar.url(:icon), :class => "img-polaroid img-comment"), user_path(comment.user)) %>
    </div>
  </td>
  <td class="comment-body"><%= link_to(comment.user.username, user_path(comment.user)) %> <%= comment.body %></td>
  <td>
    <% if can? :destroy, comment %>
      <%= link_to(option_comment_path(comment.option, comment),
                  method: :delete,
                  remote: true,
                  class: "delete_comment",
                  id: "delete_comment#{comment[:id]}") do %>
        <i class="fa fa-close icon-delete" id="icon-delete-comment<%= comment[:id] %>"></i>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/comments/_form.html.erb
<%= simple_form_for([option, comment], :remote => true, :html => {:class => "comment-form"}) do |g| %>
  <%= g.input :user_id, as: "hidden", input_html: {:value => current_user.id} %>
  <table class="table comment-form-table">
    <tr>
      <td class="comment-user-cell">
        <% if comment.new_record? %>
          <%= link_to(image_tag(current_user.avatar.url(:icon), :class => "img-polaroid"), user_path(current_user)) %>
        <% else %>
          <%= link_to(image_tag(comment.user.avatar.url(:icon), :class => "img-polaroid"), user_path(comment.user)) %>
        <% end %>
      </td>
      <td class="comment-body-cell">
        <%= g.input :body, label: false, input_html: {class: "text-comment", placeholder: t('comments._form.write_comment'), rows: 1} %>
      </td>
      <td class="comment-btn-cell">
        <%= g.button(:submit, t('buttons.submit'), class: "btn btn-primary btn-block submit_form comment-btn") %>
      </td>
    </tr>
  </table>
<% end %>

app/views/comments/_index.html.erb
<div id="comments-modal-option<%= option.id %>" class="comments-modal modal hide fade" tabindex="-1" role="dialog" aria-labelledby="comments-modal-label-option<%= option.id %>" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
      <i class="icon-remove close-login-form"></i>
    </button>
    <h3 id="comments-modal-label-option<%= option.id %>"><%= t('comments._index.title_html', option: option.name) %></h3>
  </div>

  <div id="modal-body-comments-option<%= option.id %>" class="modal-body">
    <div id="comments-pagination-option<%= option.id %>" class="center"></div>

    <table class="table comments-table">
      <tbody id="comments-option<%= option.id %>" >
        <%# render comments here %>
      </tbody>
    </table>
  </div>

  <div id="comments-form-option<%= option.id %>" class="modal-footer modal-footer-comments">
    <%# form goes here %>
  </div>
</div>

app/views/comments/create.js.erb
if ($(".comments-last_page").length == 0) {
  $("#comments-option<%=@option.id%>").children(":first").remove();
}
$("<%= escape_javascript(render @comment) %>").appendTo("#comments-option<%=@option.id%>");
$('<%="#comments-form-option#{@option.id}"%>')
  .html("<%= escape_javascript(render partial: "comments/form",
                                      locals: { option: @option,
                                                comment: @new_comment
                                              }
                              ) %>");
$('<%="#modal-body-comments-option#{@option.id}"%>').scrollTop(10000);
autoExpand('.text-comment');

app/views/comments/destroy.js.erb
$('.comment<%= @comment_id %>').slideUp(200);

app/views/comments/index.js.erb
var heightBefore = $('<%="#comments-option#{@option.id}"%>').height();
$("<%= escape_javascript(render @comments.reverse) %>").prependTo('<%="#comments-option#{@option.id}"%>');
var heightAfter = $('<%="#comments-option#{@option.id}"%>').height();

$('<%="#comments-modal-option#{@option.id}"%>').one('shown', function () {
  $('<%="#comments-form-option#{@option.id}"%>').empty();
  $("<%= escape_javascript(render(partial: "comments/form",
                                  locals: { option: @option,
                                            comment: @comment
                                          })
                          ) %>").appendTo('<%="#comments-form-option#{@option.id}"%>');
  $('<%="#modal-body-comments-option#{@option.id}"%>').scrollTop(10000);
  autoExpand('.text-comment');
  $(this).find('.text-comment').focus();
});

$('<%="#modal-body-comments-option#{@option.id}"%>').scrollTop(heightAfter - heightBefore);

// Update pagination link
<% if @comments.last_page? %>
  $('<%="#comments-pagination-option#{@option.id}"%>').html('<p class="center comments-last_page"></p>');
<% else %>
  $('<%="#comments-pagination-option#{@option.id}"%>').html("<%=j link_to_next_page(@comments, t('comments._index.next'), :remote => true, :id => "next_page-comment-option#{@option.id}", :class => "btn next_page-comments") %>");
<% end %>

$('<%="#comments-modal-option#{@option.id}"%>').modal('show');

$('<%="#comments-modal-option#{@option.id}"%>').one('hide', function () {
  $('<%="#modal-body-comments-option#{@option.id}"%>').scrollTop(10000);
});

$('<%="#comments-modal-option#{@option.id}"%>').one('hidden', function () {
  $('<%="#comments-option#{@option.id}"%>').empty();
  $('<%="#comments-form-option#{@option.id}"%>').empty();
});

app/views/comments/reload_form.js.erb
$('<%="#comments-form-option#{@option.id}"%>')
  .html("<%= escape_javascript(render partial: "comments/form",
                                      locals: { option: @option,
                                                comment: @comment
                                              }
                              ) %>");
autoExpand('.text-comment');

app/views/comments/unsigned_user.js.erb
$('#login-box').replaceWith("<%= j (render :partial => 'users/overlay_sign_in') %>");
$('#login-modal').modal('show');

jQuery(closeOverlayLoginForm);

$(document).click(function(event) {
  if (!$(event.target).closest('.login-black-box-container').length) {
    if ($('#login-box').is(":visible")) {
      $('#login-box').hide()
    }
  }
})