config/routes.rb
Moka::Application.routes.draw do
  filter :locale

  devise_for :users, controllers: {
                                    omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations"
                                  }

  devise_scope :user do
    get '/users/auth/:provider/battles/:battle_id' => 'users/omniauth_callbacks#share_battle'
    get '/users/auth/:provider/friends' => 'users/omniauth_callbacks#find_friends'
    get '/users/auth/:provider/setup', :to => 'users/omniauth_callbacks#setup'
  end

  get "users/facebook_friends" => "users#facebook_friends", :as => :user_facebook_friends
  get "users/sign_in_popup"    => "users#sign_in_popup",    :as => :user_sign_in_popup
  resources :users, :only => [:show, :index, :edit, :update] do
    resources :friendships, :only => [:create, :destroy, :index]
    resource :email_settings, :only => [:edit, :update]
  end
  get "users/:id/following" => "users#following", :as => :user_following
  get "users/:id/followers" => "users#followers", :as => :user_followers
  get "users/edit/social"   => "users#social",    :as => :user_social

  resources :battles, :except => [:index]
  get "hashtags/:hashtag" => "battles#hashtag", :as => :hashtag
  get "search(/:search)" => "searches#search", :as => :search

  resources :votes, :only => [:create]
  resources :notifications, :only => [:index]
  get "notifications_dropdown" => "notifications#dropdown", :as => :notifications_dropdown

  resources :options, :except => [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :comments, :only => [:index, :create, :destroy]
  end
  get "options/:id/votes" => "options#votes", :as => :option_votes

  get '/.well-known/acme-challenge/:id' => 'letsencrypt#challenge'

  get "locale" => 'users#locale', :as => :set_locale

  root :to => "users#home"
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  resourcify
  paginates_per 15

  belongs_to :user
  belongs_to :sender, :class_name => 'User'
  belongs_to :vote
  belongs_to :option

  attr_accessible :user, :user_id, :sender, :sender_id, :vote, :vote_id, :option

  validates :user, :presence => true
  validates :type, :presence => true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :notification

  def index
    @notifications = current_user.notifications.order(:created_at).reverse_order.page(params[:page])
    current_user.reset_unread_notifications
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def dropdown
    @notifications = current_user.notifications.order(:created_at).reverse_order.page(params[:page]).per(6)
    current_user.reset_unread_notifications
    respond_to do |format|
      format.js {}
    end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notifications_btn(user)
    if !user || user.unread_notifications == 0
      return '<div id="notifications-none"></div>'.html_safe
    else
      return "<div id=\"notifications-unread\"><p class=\"notifications-btn-text center\">#{user.unread_notifications}</p></div>".html_safe
    end
  end
end


app/views/notifications/_dropdown.html.erb
<li class="visible-desktop"><div id="notifications-group" class="btn-group">
  <%= link_to(notifications_dropdown_path(),
              id: "notifications-btn",
              class: "notifications-btn dropdown-toggle",
              "data-toggle" => "dropdown",
              remote: true
             ) do %>
    <%= notifications_btn(current_user) %>
  <% end %>

  <div class="dropdown-menu">
    <div class="span4">
      <div class="row">
        <div class="span4">
          <h4><%= t 'notifications._dropdown.title' %></h4>
        </div>
      </div>

      <div class="row">
        <div class="span4">
          <table id="notification-dropdown" class="table">
          </table>
        </div>
      </div>

      <div class="row">
        <div class="span4">
          <p class="notification-all">
            <%= link_to t('notifications._dropdown.more'), notifications_path, class: "btn btn-primary btn-block" %>
          </p>
        </div>
      </div>
    </div>
  </div>

</div></li>
<li class="hidden-desktop"><%= link_to t('notifications._dropdown.notifications'), notifications_path %></li>

app/views/notifications/dropdown.js.erb
$("#notifications-btn").html("<%= escape_javascript(notifications_btn(current_user)) %>");
$("#notification-dropdown").html("<%= escape_javascript(render @notifications) %>");
jQuery(showsUnfollowButton);

app/views/notifications/index.html.erb
<div class="span12">
  <div class="row">
    <div class="span6 offset3">
      <h4><%= t 'notifications.index.title' %></h4>
    </div>
  </div>

  <div class="row">
    <div class="span6 offset3">
      <table id="notification-index" class="table">
        <%= render @notifications %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="span6 offset3">
      <p class="notification-pagination">
        <% if @notifications.last_page? %>
          <p class='center notification-last_page'><%= image_tag("watermark_small.png") %></p>
        <% else %>
          <%= link_to_next_page(@notifications, t('notifications.index.next'), :remote => true, :class => "next_page") %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/notifications/index.js.erb
$("<%= escape_javascript(render @notifications) %>").appendTo("#notification-index");

// Update pagination link
<% if @notifications.last_page? %>
  $('.notification-pagination').html('<p class="center notification-last_page"><%= image_tag("watermark_small.png") %></p>');
<% else %>
  $('.notification-pagination').html("<%=j link_to_next_page(@notifications, t('notifications.index.next'), :remote => true, :class => "next_page") %>");
<% end %>