config/routes.rb
Moka::Application.routes.draw do
  filter :locale

  devise_for :users, controllers: {
                                    omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations"
                                  }

  devise_scope :user do
    get '/users/auth/:provider/battles/:battle_id' => 'users/omniauth_callbacks#share_battle'
    get '/users/auth/:provider/friends' => 'users/omniauth_callbacks#find_friends'
    get '/users/auth/:provider/setup', :to => 'users/omniauth_callbacks#setup'
  end

  get "users/facebook_friends" => "users#facebook_friends", :as => :user_facebook_friends
  get "users/sign_in_popup"    => "users#sign_in_popup",    :as => :user_sign_in_popup
  resources :users, :only => [:show, :index, :edit, :update] do
    resources :friendships, :only => [:create, :destroy, :index]
    resource :email_settings, :only => [:edit, :update]
  end
  get "users/:id/following" => "users#following", :as => :user_following
  get "users/:id/followers" => "users#followers", :as => :user_followers
  get "users/edit/social"   => "users#social",    :as => :user_social

  resources :battles, :except => [:index]
  get "hashtags/:hashtag" => "battles#hashtag", :as => :hashtag
  get "search(/:search)" => "searches#search", :as => :search

  resources :votes, :only => [:create]
  resources :notifications, :only => [:index]
  get "notifications_dropdown" => "notifications#dropdown", :as => :notifications_dropdown

  resources :options, :except => [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :comments, :only => [:index, :create, :destroy]
  end
  get "options/:id/votes" => "options#votes", :as => :option_votes

  get '/.well-known/acme-challenge/:id' => 'letsencrypt#challenge'

  get "locale" => 'users#locale', :as => :set_locale

  root :to => "users#home"
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    if not validate_omniauth_data(request.env["omniauth.auth"], :facebook)
      respond_to do |format|
        format.js { render "users/facebook_share_error" }
        format.html { redirect_to new_user_registration_url }
      end
      return
    end

    #####################################################
    # SHARE BATTLE
    #####################################################

    if request.env["omniauth.params"] &&
       request.env["omniauth.params"]["source"] &&
       request.env["omniauth.params"]["source"] == "share" &&
       request.env["omniauth.params"]["battle_id"]
      share_battle_on_facebook(request.env["omniauth.auth"].uid, request.env["omniauth.params"]["battle_id"])
      redirect_to battle_path(request.env["omniauth.params"]["battle_id"])
      return
    elsif request.env["omniauth.params"] &&
       request.env["omniauth.params"]["source"] &&
       request.env["omniauth.params"]["source"] == "share"
      flash[:alert] = I18n.t('messages.error_share', provider: "Facebook")
      redirect_to root_path
      return
    end


    #####################################################
    # FIND FACEBOOK FRIENDS
    #####################################################

    if request.env["omniauth.params"] &&
       request.env["omniauth.params"]["source"] &&
       request.env["omniauth.params"]["source"] == "find_friends" &&
       request.env["omniauth.auth"].credentials &&
       current_user
      friends = current_user.find_friends_from_facebook(request.env["omniauth.auth"].credentials)
      update_friends_list(current_user, friends)
      redirect_to user_facebook_friends_path
      return
    elsif request.env["omniauth.params"] &&
       request.env["omniauth.params"]["source"] &&
       request.env["omniauth.params"]["source"] == "find_friends" &&
       request.env["omniauth.auth"].credentials
      flash[:alert] = I18n.t('messages.error_find_friends_not_logged', provider: "Facebook")
      redirect_to root_path
      return
    end


    #####################################################
    # SIGN IN
    #####################################################

    # Email is required. Ask again if it is not provided
    if (not request.env["omniauth.auth"].info.email) || (request.env["omniauth.auth"].info.email.blank?)
      redirect_to "/users/auth/facebook?auth_type=rerequest&scope=email"
      return
    end

    @user = User.find_for_oauth(request.env["omniauth.auth"], current_user)

    if @user.nil?
      # Error: User already exists
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      set_flash_message(:alert, :failure, kind: :Facebook, reason: I18n.t('messages.omniauth_already_exists_error')) if is_navigational_format?
      redirect_to root_path

    elsif @user.persisted?
      # Success: User created successfully
      if @user.confirmed?
        sign_in(@user, event: :authentication)
        set_flash_message(:notice, :success, kind: :Facebook) if is_navigational_format?
      else
        flash[:notice] = I18n.t('devise.registrations.signed_up_but_unconfirmed')
      end

      redirect_to request.env['omniauth.origin'] || stored_location_for(resource) || root_path

    else
      # Error: Could not persist user
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      set_flash_message(:alert, :failure, kind: :Facebook, reason: I18n.t('messages.omniauth_error')) if is_navigational_format?
      redirect_to new_user_registration_url

    end
  end

  def share_battle
    authorize! :share, Battle.find_by_id(params[:battle_id])

    if params[:provider] == "facebook"
      flash[:scope] = 'public_profile,user_friends,email,publish_actions'
      flash[:display] = 'popup'
      redirect_to "/users/auth/facebook?source=share&battle_id=#{params[:battle_id]}"
    else
      flash[:alert] = I18n.t('messages.error_share', provider: params[:provider])
      redirect_to root_path
    end
  end

  def find_friends
    authorize! :find_friends, User

    if params[:provider] == "facebook"
      flash[:scope] = 'public_profile,user_friends,email'
      flash[:display] = 'popup'
      redirect_to "/users/auth/facebook?source=find_friends"
    else
      flash[:alert] = I18n.t('messages.error_find_friends', provider: params[:provider])
      redirect_to root_path
    end
  end

  def setup
    request.env['omniauth.strategy'].options['scope'] = flash[:scope] || request.env['omniauth.strategy'].options['scope']
    request.env['omniauth.strategy'].options['display'] = flash[:display] || request.env['omniauth.strategy'].options['display']
    render :text => "Setup complete.", :status => 404
  end

private
  def validate_omniauth_data(auth, provider)
    if (not auth) ||
       (not auth.info) ||
       (not auth.uid) ||
       (not auth.provider) ||
       (auth.provider.to_sym != provider) ||
       (not auth.credentials)
      set_flash_message(:alert, :failure, kind: provider, reason: I18n.t('messages.omniauth_unknown_error')) if is_navigational_format?
      return false
    end
    return true
  end

  def share_battle_on_facebook(uid, battle_id)
    authorize! :share, Battle.find_by_id(battle_id)

    params = {
      :client_id => ENV['FACEBOOK_KEY'],
      :client_secret => ENV['FACEBOOK_SECRET'],
      :grant_type => "client_credentials"
    }
    uri = URI("https://graph.facebook.com/oauth/access_token?#{params.to_query}")
    response = Net::HTTP.get(uri)
    access_token = Rack::Utils.parse_nested_query(response)["access_token"]
    unless access_token.nil?
      uri = URI('https://graph.facebook.com')
      Net::HTTP.post_form(uri,
                          'id' => canonical_battle_url(battle_id),
                          'scrape' => 'true',
                          'access_token' => "#{access_token}",
                          'max' => '500')

      @graph = Koala::Facebook::API.new(access_token)
      @graph.put_connections(uid, "batalharia:create", battle: canonical_battle_url(battle_id))
    end
  end

  def update_friends_list(user, friends)
    friends.each do |friend|
      user.update_facebook_friend(friend)
    end
  end

  def canonical_battle_url(battle_id)
    return "https://batalharia.com#{battle_path(battle_id).sub("\/#{@locale}", "")}"
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # Overwrite update_resource to let users to update their user without giving their password
  def update_resource(user, params)
    if user.identities.count > 0
      params.delete("current_password")
      user.update_without_password(params)
    else
      user.update_with_password(params)
    end
  end

  def create
    super do |user|
      user.email_settings = EmailSettings.create(user_id: user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :update, :social, :facebook_friends]
  load_and_authorize_resource :user, :find_by => :username, :except => [:home, :social, :locale, :facebook_friends, :sign_in_popup]

  def locale
    referer_path = URI(request.referer).path
    if /^\/(en|pt-BR)(\/|$|\?)/ =~ referer_path
      redirect_to referer_path.sub(/\/[^\/]+[\/]?/, "/#{I18n.locale}/")
    else
      redirect_to "/#{I18n.locale}#{referer_path}"
    end
  end

  def home
    @user = current_user
    if not @user
      respond_to do |format|
        format.html { render 'users/cover', :layout => "cover" }
      end
      return
    end

    authorize! :home, @user

    @filter = params[:filter] || 'all'

    @battles = Battle.user_home(@user, params[:page])
    @voted_for = current_user.voted_for_options(@battles)
    @victorious = Battle.victorious(@battles)
    @top_comments = Battle.top_comments(@battles)
    @vote = Vote.new()
    @find_friends = true
    @render_welcome = @user.welcome?
    @render_battle_help = @user.first_battle?
    respond_to do |format|
      format.js { render "users/load_more_battles" }
      format.html {}
    end
  end

  def show
    @battles = @user.sorted_battles(params[:page])

    @filter = params[:filter] || 'all'

    @voted_for = {}
    if current_user
      @voted_for = current_user.voted_for_options(@battles)
      @render_welcome = current_user.welcome?
      @render_battle_help = current_user.first_battle?
    end
    @victorious = Battle.victorious(@battles)
    @top_comments = Battle.top_comments(@battles)

    @vote = Vote.new()
    @number_of_following = @user.friends.count
    @number_of_followers = @user.inverse_friends.count
    respond_to do |format|
      format.js { render "users/load_more_battles" }
      format.html {}
    end
  end

  def index
    @search = params[:search] || session[:user_search]
    if (@search) && (@search != "")
      session[:user_search] = @search
      @users = User.search(@search, params[:page])
      respond_to do |format|
        format.js {}
        format.html {}
      end
    else
      flash[:alert] = I18n.t('messages.invalid_search')
      redirect_to root_url
    end
  end

  def following
    @users = @user.following(params[:page])
    respond_to do |format|
      format.js { render('users/index') }
      format.html {}
    end
  end

  def followers
    @users = @user.followers(params[:page])
    respond_to do |format|
      format.js { render('users/index') }
      format.html {}
    end
  end

  def edit
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def update
    if (not params[:user]) || (not params[:user][:avatar]) || (not @user.update_attributes(:avatar => params[:user][:avatar]))
      flash[:alert] = I18n.t('messages.invalid_image')
    end
    redirect_to user_path(@user)
  end

  def social
    @user = current_user
    authorize! :social, @user
  end

  def facebook_friends
    @user = current_user
    authorize! :facebook_friends, @user

    @users = @user.get_facebook_friends(params[:page])
    @find_friends = true
    respond_to do |format|
      format.js { render('users/index') }
      format.html {}
    end
  end

  def sign_in_popup
    authorize! :sign_in_popup, User
    respond_to do |format|
      format.js {}
      format.html { redirect_to new_user_session_path }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_button_for(user, btn_classes = "btn-large")
    if !current_user
      return (link_to(user_sign_in_popup_path, remote: true, :class => "btn #{btn_classes} btn-block btn-follow") do
               "<i class=\"icon-plus\"></i> #{I18n.t('users.show.follow')}".html_safe
             end).html_safe
    end

    if current_user == user
      return link_to(t('users.show.edit_account'), edit_user_registration_path, :class => "btn btn-info btn-block #{btn_classes} btn-edit-profile")
    else
      if current_user.is_friends_with?(user)
        friendship = current_user.get_friendship_with(user)
        return link_to(user_friendship_path(current_user, :id => friendship.id), method: :delete, remote: true, :class => "btn btn-success btn-unfollow #{btn_classes} btn-block") do
                 "<span class=\"following\"><i class=\"icon-ok icon-inverse\"></i> #{I18n.t('users.show.following')}</span>"\
                 "<span class=\"unfollow\"><i class=\"icon-remove icon-inverse\"></i> #{I18n.t('users.show.unfollow')}</span>".html_safe
               end
      else
        return (link_to(user_friendships_path(current_user, :friend_id => user.id), method: :post, remote: true, :class => "btn #{btn_classes} btn-block btn-follow") do
                 "<i class=\"icon-plus\"></i> #{I18n.t('users.show.follow')}".html_safe
               end).html_safe
      end
    end
  end

  def mini_user_button_for(user)
    if !current_user
      return (link_to(user_sign_in_popup_path, remote: true, :class => "btn btn-block btn-follow") do
               "<i class=\"icon-plus\"></i><i class=\"icon-user\"></i>".html_safe
             end).html_safe
    end

    if current_user == user
      return link_to(edit_user_registration_path, :class => "btn btn-info btn-block btn-edit-profile") do
               "<i class=\"icon-edit\"></i>".html_safe
             end
    else
      if current_user.is_friends_with?(user)
        friendship = current_user.get_friendship_with(user)
        return link_to(user_friendship_path(current_user, :id => friendship.id), method: :delete, remote: true, :class => "btn btn-success btn-unfollow btn-block") do
                 "<span class=\"following\"><i class=\"icon-ok icon-inverse\"></i><i class=\"icon-user icon-inverse\"></i></span>"\
                 "<span class=\"unfollow\"><i class=\"icon-remove icon-inverse\"></i><i class=\"icon-user icon-inverse\"></i></span>".html_safe
               end
      else
        return (link_to(user_friendships_path(current_user, :friend_id => user.id), method: :post, remote: true, :class => "btn btn-block btn-follow") do
                 "<i class=\"icon-plus\"></i><i class=\"icon-user\"></i>".html_safe
               end).html_safe
      end
    end
  end

  def user_name_for(user)
    return user.name || user.username
  end

  def from_omniauth?(user)
    return user && user.identities && user.identities.count > 0
  end

  def find_facebook_friends_button(message)
    if user_signed_in?
      return link_to('/users/auth/facebook/friends',
                 :id => 'facebook-friends-find',
                 :class => 'btn btn-primary btn-large btn-facebook btn-block') do
        "<table class=\"facebook-login-table\">"\
          "<tr>"\
            "<td>#{ fa_icon "facebook-square", class: "fa-2x" }</td>"\
            "<td></td>"\
            "<td>#{ message }</td>"\
          "</tr>"\
        "</table>".html_safe
      end
    else
      return ""
    end
  end

  def find_facebook_friends_button_mini(message)
    if user_signed_in?
      return link_to('/users/auth/facebook/friends',
                 :class => 'btn btn-primary btn-facebook') do
          "#{ fa_icon "facebook-square", class: "fa-1x" } "\
          "#{ message }".html_safe
      end
    else
      return ""
    end
  end
end

app/views/users/_avatar.html.erb
<div class="avatar-box">
  <div class="row">
    <div class="span2 avatar-form-sizeable">
      <div class="picture-box">
        <% if can? :update, user %>
          <%= link_to(edit_user_path(user), :remote => true, :class => "btn-edit-user-avatar") do %>
            <span class="current-avatar"><%= image_tag(user.avatar.url(:medium)) %></span>
            <span class="icon-edit-avatar edit_picture"><i class="icon-edit pull-left"></i></span>
          <% end %>
        <% else %>
          <%= image_tag(user.avatar.url(:medium)) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if can? :update, user %>
  <div id="user_form" style="display:none;"></div>
<% end %>

app/views/users/_edit_nav.html.erb
<ul class="nav nav-tabs">
  <li class=<%= is_active?(edit_user_registration_path) %>>
    <%= link_to(t('users._edit_nav.account'),
                edit_user_registration_path,
                id: 'edit_user_registration_tab') %>
  </li>
  <li class=<%= is_active?(edit_user_path(@user)) %>>
    <%= link_to(t('users._edit_nav.profile'),
                edit_user_path(@user),
                id: 'user_edit_tab') %>
  </li>
  <li class=<%= is_active?(user_social_path) %>>
    <%= link_to(t('users._edit_nav.social'),
                user_social_path,
                id: 'user_social_tab') %>
  </li>
  <li class=<%= is_active?(edit_user_email_settings_path(@user)) %>>
    <%= link_to(t('users._edit_nav.email_settings'),
                edit_user_email_settings_path(@user),
                id: 'user_email_settings_tab') %>
  </li>
</ul>

app/views/users/_form.html.erb
<%= form_for(user, :html => { :class => "avatar_form", :multipart => true }) do |f| %>

  <div class="row">
    <div class="span2">

      <div class="avatar-box editable">
        <div class="row">
          <div class="span2 avatar-form-sizeable">
            <div class="picture-box">
              <div class="current_picture">
                <div class="picture_preview">
                  <div class="picture_preview_container">
                  </div>
                </div>
                <%= image_tag f.object.avatar.url(:medium), :class => "existing_image" %>
              </div>
              <%= f.file_field(:avatar, accept: 'image/png,image/gif,image/jpeg,image/jpg', :class => 'upload_picture') %>
              <div class="delete_picture delete-picture-user">
                <i class="icon-remove pull-right"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="span2">
      <%= f.button(t('buttons.update'), :class => "btn btn-primary btn-block submit_form") %>
    </div>
  </div>

<% end %>

app/views/users/_overlay_sign_in.html.erb
<div id="login-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="login-overlay-title" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
      <i class="icon-remove close-login-form"></i>
    </button>
    <h3 id="login-overlay-title" class="center"><%= t('users._overlay_sign_in.title') %></h3>
  </div>
  <div class="modal-body">

    <div class="facebook-login-box">
      <%= link_to('/users/auth/facebook',
                  :id => 'facebook-sign-in',
                  :class => 'btn btn-primary btn-facebook btn-large btn-block') do %>
        <table class="facebook-login-table">
          <tr>
            <td><%= fa_icon "facebook-square", class: "fa-1x" %></td>
            <td></td>
            <td><%= t('devise.shared._links.omniauth', provider: :Facebook) %></td>
          </tr>
        </table>
      <% end %>
    </div>

    <h5 class="divider"><span class="divider-text"><%= t('messages.or') %></span></h5>

    <%= render :partial => 'devise/sessions/inline_form',
               :locals => {
                 :resource => :user,
                 :resource_name => :user
               } %>

    <p><%= t('users._overlay_sign_in.not_a_member_html', :link => link_to(t('users._overlay_sign_in.sign_up'), new_registration_path(:user))) %></p>
    <p><%= link_to t('devise.shared._links.recover'), new_password_path(:user) %></p>

  </div>
</div>


app/views/users/_user.html.erb
<tr id="user<%= user.id %>-search" class="user-search">
  <td><%= link_to(image_tag(user.avatar.url(:small), :class => "img-polaroid"), user_path(user)) %></td>
  <td>
    <h5><%= link_to(user.username, user_path(user)) %></h5>
    <p class="name"><%= user.name %></p>
  </td>
  <td>
    <div class="span3 pull-right">
      <div id="user-button<%= user.id %>" class="user-button">
        <%= user_button_for(user) %>
      </div>
    </div>
  </td>
</tr>

app/views/users/_welcome.html.erb
<div class="alert alert-info fade in alert-block alert-welcome">
  <a href="#" class="close" data-dismiss="alert" href="#">&times;</a>
  <h3><%= t('users._welcome.title') %></h3>
  <p><%= t('users._welcome.start') %></p>
  <p><%= t('users._welcome.find_friends_html') %></p>
  <p><%= t('users._welcome.find_battles_html') %></p>
  <p>
    <%= t('users._welcome.find_facebook_html') %>
    <%= find_facebook_friends_button_mini(t('buttons.find_facebook_friends')) %>
  </p>
</div>

app/views/users/edit.html.erb
<%= render 'users/edit_nav' %>

<div class="span12 edit-avatar-container">
  <h3><%= t('.title') %></h3>

  <%= render :partial => "users/form", :locals => { :user => @user } %>
</div>

app/views/users/followers.html.erb
<div class="span12">
  <div class="row">

    <div class="span2">

      <div class="row">
        <div class="span2">
          <%= render :partial => "users/avatar", :locals => { :user => @user } %>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div id="user-button<%= @user.id %>" class="user-button profile-user-button">
            <%= user_button_for(@user, "") %>
          </div>
        </div>
      </div>

    </div>

    <div class="span10">
      <div class="row">
        <div class="span6">
          <div class="row">
            <div class="span4">
              <p class="username">
                <%= link_to(@user.username, user_path(@user)) %>
              </p>
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <p class="name"><%= @user.name %></p>
            </div>
          </div>
        </div>

        <div class="span4 hidden-phone">
          <%= find_facebook_friends_button(t('buttons.find_facebook_friends')) %>
        </div>

      </div>
    </div>

  </div>

  <div class="row">
    <div class="span4 offset4">
      <h2 class="center"><%= I18n.t('users.followers.title') %></h2>
    </div>
  </div>

  <div class="row">
    <%= render :partial => "friendships/index", :locals => { :friends => @users }  %>
  </div>
</div>

app/views/users/following.html.erb
<div class="span12">
  <div class="row">

    <div class="span2">

      <div class="row">
        <div class="span2">
          <%= render :partial => "users/avatar", :locals => { :user => @user } %>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div id="user-button<%= @user.id %>" class="user-button profile-user-button">
            <%= user_button_for(@user, "") %>
          </div>
        </div>
      </div>

    </div>

    <div class="span10">
      <div class="row">
        <div class="span6">
          <div class="row">
            <div class="span4">
              <p class="username">
                <%= link_to(@user.username, user_path(@user)) %>
              </p>
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <p class="name"><%= @user.name %></p>
            </div>
          </div>
        </div>

        <div class="span4 hidden-phone">
          <%= find_facebook_friends_button(t('buttons.find_facebook_friends')) %>
        </div>

      </div>
    </div>

  </div>

  <div class="row">
    <div class="span4 offset4">
      <h2 class="center"><%= I18n.t('users.following.title') %></h2>
    </div>
  </div>

  <div class="row">
    <%= render :partial => "friendships/index", :locals => { :friends => @users }  %>
  </div>
</div>

app/views/users/index.html.erb
<div class="span12">
  <div class="row">
    <div class="span8 offset2">
      <h4><%= t '.title' %></h4>
    </div>
  </div>

  <div class="row">
    <div class="span8 offset2">
      <table id="users-index" class="table">
        <%= render @users %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="span8 offset2">
      <p class="user-pagination">
        <% if @users.last_page? %>
          <p class='center user-last_page'><%= image_tag("watermark_small.png") %></p>
        <% else %>
          <%= link_to_next_page(@users, t('.next'), :remote => true, :class => "next_page") %>
        <% end %>
      </p>
    </div>
  </div>
</div>


<% content_for :head do %>
  <%# for Google %>
  <meta name="description" content="<%= t('og.description_long') %>">
  <meta name="keywords" content="<%= t('og.keywords') %>">
  <meta name="application-name" content="Batalharia">

  <%# for Facebook %>
  <meta property="og:title" content="<%= t('og.title') %>">
  <meta property="og:url" content="https://batalharia.com">
  <meta property="fb:app_id" content="<%= ENV['FACEBOOK_KEY'] %>">
  <meta property="og:type" content="website">
  <meta property="og:description" content="<%= t('og.description_long') %>">
  <meta property="og:image" content="<%= image_url("logo_banner.png") %>">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:site_name" content="Batalharia">
  <meta property="og:locale" content="<%= I18n.t('og.locale') %>">
  <meta property="og:locale:alternate" content="<%= I18n.t('og.locale_alternate1') %>">
  <meta property="og:rich_attachment" content="true">

  <%# for Twitter %>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@batalharia">
  <meta name="twitter:url" content="https://batalharia.com">
  <meta name="twitter:title" content="<%= t('og.title') %>">
  <meta name="twitter:description" content="<%= t('og.description_short') %>">
  <meta name="twitter:image" content="<%= image_url("logo_box.png") %>">
<% end %>

app/views/users/index.js.erb
$("<%= escape_javascript(render @users) %>").appendTo("#users-index");

// Update pagination link
<% if @users.last_page? %>
  <% if @find_friends %>
    $('.user-pagination').html('<div class="row"><div class="span4 offset2 find-facebook-friends-container"><%= find_facebook_friends_button(t('buttons.update_facebook_friends')) %></div></div><div class="row"><p class="center user-last_page"><%= image_tag("watermark_small.png") %></p></div>');
  <% else %>
    $('.user-pagination').html('<p class="center user-last_page"><%= image_tag("watermark_small.png") %></p>');
  <% end %>
<% else %>
  $('.user-pagination').html("<%=j link_to_next_page(@users, t('users.index.next'), :remote => true, :class => "next_page") %>");
<% end %>

jQuery(showsUnfollowButton);

app/views/users/show.html.erb
<div class="span12">

  <% if @render_welcome %>
    <%= render 'users/welcome' %>
  <% end %>

  <div class="row">

    <div class="span2">
      <div class="row">
        <div class="span2">
          <%= render :partial => "users/avatar", :locals => { :user => @user } %>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div id="user-button<%= @user.id %>" class="user-button profile-user-button">
            <%= user_button_for(@user, "") %>
          </div>
        </div>
      </div>

    </div>

    <div class="span10">
      <div class="row">
        <div class="span4">
          <div class="row">
            <div class="span4">
              <p class="username"><%= @user.username %></p>
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <p class="name"><%= @user.name %></p>
            </div>
          </div>
        </div>

        <div class="span3">
          <%= link_to(user_following_path(@user), :class => "btn btn-info btn-block btn-large btn-following") do
            "#{I18n.t('users.show.following_list', :count => @number_of_following)}"
          end %>
        </div>

        <div class="span3">
          <%= link_to(user_followers_path(@user), :class => "btn btn-info btn-block btn-large btn-followers") do
            "#{I18n.t('users.show.followers_list', :count => @number_of_followers)}"
          end %>
        </div>
      </div>

    </div>
  </div>


  <% if current_user == @user %>
    <%= render 'battles/new' %>
  <% end %>
  <%= render 'battles/index' %>

</div>


<% content_for :head do %>
  <%# for Google %>
  <meta name="description" content="<%= t('og.profile_title', user: @user.username) %>">
  <meta name="keywords" content="<%= t('og.keywords') %>">
  <meta name="author" content="<%= @user.username %>">
  <meta name="application-name" content="Batalharia">

  <%# for Facebook %>
  <meta property="og:title" content="<%= t('og.profile_title', user: @user.username) %>">
  <meta property="og:url" content="<%= canonical_url(user_url(@user.username)) %>">
  <meta property="fb:app_id" content="<%= ENV['FACEBOOK_KEY'] %>">
  <meta property="og:type" content="website">
  <meta property="og:description" content="<%= t('og.profile_description', user: @user.username) %>">
  <meta property="og:image" content="<%= image_url("logo_banner.png") %>">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:site_name" content="Batalharia">
  <meta property="og:locale" content="<%= I18n.t('og.locale') %>">
  <meta property="og:locale:alternate" content="<%= I18n.t('og.locale_alternate1') %>">
  <meta property="og:rich_attachment" content="true">

  <%# for Twitter %>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@batalharia">
  <meta name="twitter:url" content="<%= canonical_url(user_url(@user.username)) %>">
  <meta name="twitter:title" content="<%= t('og.profile_title', user: @user.username) %>">
  <meta name="twitter:description" content="<%= t('og.profile_description', user: @user.username) %>">
  <meta name="twitter:image" content="<%= image_url("logo_box.png") %>">
<% end %>