config/routes.rb
Moka::Application.routes.draw do
  filter :locale

  devise_for :users, controllers: {
                                    omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations"
                                  }

  devise_scope :user do
    get '/users/auth/:provider/battles/:battle_id' => 'users/omniauth_callbacks#share_battle'
    get '/users/auth/:provider/friends' => 'users/omniauth_callbacks#find_friends'
    get '/users/auth/:provider/setup', :to => 'users/omniauth_callbacks#setup'
  end

  get "users/facebook_friends" => "users#facebook_friends", :as => :user_facebook_friends
  get "users/sign_in_popup"    => "users#sign_in_popup",    :as => :user_sign_in_popup
  resources :users, :only => [:show, :index, :edit, :update] do
    resources :friendships, :only => [:create, :destroy, :index]
    resource :email_settings, :only => [:edit, :update]
  end
  get "users/:id/following" => "users#following", :as => :user_following
  get "users/:id/followers" => "users#followers", :as => :user_followers
  get "users/edit/social"   => "users#social",    :as => :user_social

  resources :battles, :except => [:index]
  get "hashtags/:hashtag" => "battles#hashtag", :as => :hashtag
  get "search(/:search)" => "searches#search", :as => :search

  resources :votes, :only => [:create]
  resources :notifications, :only => [:index]
  get "notifications_dropdown" => "notifications#dropdown", :as => :notifications_dropdown

  resources :options, :except => [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :comments, :only => [:index, :create, :destroy]
  end
  get "options/:id/votes" => "options#votes", :as => :option_votes

  get '/.well-known/acme-challenge/:id' => 'letsencrypt#challenge'

  get "locale" => 'users#locale', :as => :set_locale

  root :to => "users#home"
end

app/models/option.rb
class Option < ActiveRecord::Base
  resourcify

  belongs_to :battle
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
  has_many :comments, dependent: :destroy

  attr_accessible :name, :picture, :id
  has_attached_file :picture, :styles => {
                                :facebook => {
                                  :geometry => "1200x630#",
                                  :animated => false
                                },
                                :medium => {
                                  :geometry => "370x370#",
                                  :animated => false
                                },
                                :thumb => {
                                  :geometry => "100x100#",
                                  :animated => false
                                },
                                :icon => {
                                  :geometry => "44x44#",
                                  :animated => false
                                }
                              }

  validates :name, :presence => true
  validates :name, :length   => { maximum: 40 }
  validates_attachment :picture, :presence     => true,
                                 :content_type => { :content_type => /\Aimage\/.*\Z/ },
                                 :size         => { :in => 0..20.megabytes }

  def number_of_votes
    return votes.count
  end

  def ordered_votes(page)
    return self.votes.order(:created_at).page(page)
  end

  def ordered_comments(page)
    return self.comments.order(:created_at).reverse_order.page(page)
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  load_and_authorize_resource :option

  def votes
    if !current_user
      respond_to do |format|
        format.js { render 'votes/unsigned_user' }
      end
      return
    end

    @votes = @option.ordered_votes(params[:page])
    respond_to do |format|
      format.js {}
    end
  end

end

app/helpers/options_helper.rb
module OptionsHelper
  def fill_if_voted(option_id, content)
    if @voted_for && @voted_for[option_id]
      return content
    end
    return ""
  end

  def fill_if_victorious(option_id, content, current)
    if @victorious && @victorious[option_id] && (not current)
      return content
    end
    return ""
  end
end

app/views/options/_comments.html.erb
<div class="option-sizeable span<%= size %>">
  <% if comments[option.id].count > 2 %>
    <h5 class="comments-title">
      <%= link_to(t('options._comments.previous_comments'), option_comments_path(option), :remote => true, :id => "previous-comments-option#{option.id}") %>
    </h5>
  <% else %>
    <div class="no-comments"></div>
  <% end %>
  <table class="table top-comments-table">
    <tbody id="top-comments-option<%= option.id %>" >
      <%= render comments[option.id].take(2) %>
    </tbody>
  </table>


  <table class="table comment-form-table">
    <tr>
      <td class="new-comment-user-cell">
        <% if current_user %>
          <div class="comment-avatar">
            <%= link_to(image_tag(current_user.avatar.url(:icon), :class => "img-polaroid"), user_path(current_user)) %>
          </div>
        <% end %>
      </td>
      <td class="new-comment-body-cell">
        <input type="text" class="new-comment" placeholder="<%= t('options._comments.write_comment') %>">
      </td>
    </tr>
  </table>

</div>

app/views/options/_option.html.erb
<div id="option<%= option.id %>">
  <div class="option-sizeable option-offsetable span<%= size %> offset<%= offset %>">

    <div class="option-outer-box">
      <%= simple_form_for(@vote, remote: true, html: {id: "new_vote_#{battle.id}_#{option.id}"}) do |f| %>
        <%= f.input(:option_id, :as => :hidden, input_html: {value: option.id}) %>
        <%= f.button(:submit, t('buttons.vote'), :class => "vote_button btn btn-primary btn-large") %>
      <% end %>

      <div class="vote_picture_frame <%= if battle.current?
                                           "current_battle"
                                         end %> <%= fill_if_voted(option.id, "outer_selected_picture") %> <%= fill_if_victorious(option.id, "outer_victorious_picture", battle.current?) %>">

        <div id="<%="vote_option#{option.id}"%>" class="vote_picture <%= fill_if_voted(option.id, "selected_picture") %> <%= fill_if_victorious(option.id, "victorious_picture", battle.current?) %>">

          <div class="option-box <%= fill_if_voted(option.id, "selected_box") %> <%= fill_if_victorious(option.id, "victorious_box", battle.current?) %>">
            <div class="row">
              <div class="option-sizeable span<%= size %>">
                <div class="picture-box">
                  <%= image_tag option.picture.url(:medium) %>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>

      <div class="row">
        <div class="option-sizeable span<%= size %>">
          <table>
            <tr>
              <td>
                <span class="fa-stack vote-icon <%= if battle.current?
                              "current_battle"
                            end %>">
                  <i class="fa fa-square fa-stack-2x"></i>
                  <i class="fa fa-check vote-icon-check fa-stack-1x <%= fill_if_voted(option.id, "selected_icon") %> fa-inverse"></i>
                </span>
              </td>
              <td>
                <%= link_to(option_comments_path(option), remote: true, id: "btn-comments-option#{option.id}", class: "btn-comments") do %>
                  <span class="fa-stack comment-icon">
                    <i class="fa fa-square fa-stack-2x"></i>
                    <i class="fa fa-comment fa-inverse fa-stack-1x"></i>
                  </span>
                <% end %>
              </td>
              <td>
                <h3 class="center option-name"><%= auto_link_hashtags(option.name, :hashtag_url_base => hashtag_path("")).html_safe %></h3>
              </td>
            </tr>
          </table>
        </div>
      </div>

      <% if can? :show_results, battle %>
        <%= render :partial => 'votes/results', :locals => { :option => option, :votes => option.number_of_votes, :total_votes => battle.number_of_votes, :size => size } %>
      <% else %>
        <div id='<%="results#{option.id}"%>' style='display:none;'></div>
      <% end %>

      <div class="row">
        <%= render :partial => 'options/comments', :locals => { :option => option, :comments => @top_comments, :comment => @new_comment, :size => size } %>
      </div>

      <div class="row">
        <%= render('comments/box', option: option, size: size) %>
      </div>
    </div>

    <div class="row visible-phone">
      <div class="option-sizeable span<%= size %>">
        <div class="option-bottom-margin"></div>
      </div>
    </div>

  </div>

</div>

app/views/options/_options_form.html.erb
<div id="options_container" class="span12 <%= @battle_options_error %>">
  <div class="row">

    <div id="<%= @options_id %>" class="options">
      <%= f.simple_fields_for(:options) %>
    </div>

    <div class="span4 option-form-sizeable new-option-outer">
      <div class="new-option-box option-box-editable add-option-box">
        <div class="add_new_option_container">
          <%= f.link_to_add(:options, {:id => "add_new_option",
                                       :class => "btn btn-inverse btn-large",
                                       :data => {:target => "##{@options_id}", :limit => 6}
                                      }) do %>
            <i class="icon-plus icon-inverse"></i><%= " #{t 'battles._form.add_option'}" %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>
<div id="battle-options-error" class="span12 text-error" style="display:none;">
  <p class="pull-right"><%= t('messages.min_options') %></p>
</div>

app/views/options/votes.js.erb
$("<%= escape_javascript(render @votes) %>").appendTo('<%="#votes-option#{@option.id}"%>');

// Update pagination link
<% if @votes.last_page? %>
  $('<%="#vote-pagination-option#{@option.id}"%>').html('<p class="center vote-last_page"></p>');
<% else %>
  $('<%="#vote-pagination-option#{@option.id}"%>').html("<%=j link_to_next_page(@votes, t('votes._index.next'), :remote => true, :id => "next_page-option#{@option.id}", :class => "btn next_page-option") %>");
<% end %>

$('<%="#votes-modal-option#{@option.id}"%>').modal('show');

$('<%="#votes-modal-option#{@option.id}"%>').one('hide', function () {
  $('<%="#modal-body-option#{@option.id}"%>').scrollTop(0);
});

$('<%="#votes-modal-option#{@option.id}"%>').one('hidden', function () {
  $('<%="#votes-option#{@option.id}"%>').empty();
});

jQuery(showsUnfollowButton);